name: MLflow CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install mlflow scikit-learn pandas

    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local

    - name: Isolate Model Artifact
      run: |
        # 1. Cari folder model asli di dalam mlruns
        ORIGINAL_MODEL=$(find . -type d -path "*/artifacts/model" | head -n 1)
        echo "Ditemukan di: $ORIGINAL_MODEL"
        
        # 2. Copy utuh ke luar agar bebas dari isu permission & Docker context
        cp -r $ORIGINAL_MODEL ./deploy_model
        
        # 3. Print isinya ke log GitHub untuk bukti bahwa file MLmodel ADA
        echo "Isi folder deploy_model:"
        ls -la ./deploy_model

    - name: Build Docker Model
      run: |
        # Build dari folder yang sudah diisolasi dan NAIKKAN TAG KE v2
        mlflow models build-docker -m ./deploy_model -n "${{ secrets.DOCKER_USERNAME }}/churn-model:v2"

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/churn-model:v2