name: MLflow CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

env:
  MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/mlruns"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install mlflow scikit-learn pandas

    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local

    - name: Isolate Model Artifact (The /tmp Hunter)
      run: |
        echo "Menyisir folder /tmp untuk memburu model yang tertinggal..."
        # Mencari di seluruh sistem Temp milik Ubuntu (menyembunyikan pesan error permission)
        ORIGINAL_MODEL=$(find /tmp -type d -path "*/artifacts/model" 2>/dev/null | head -n 1)
        
        if [ -z "$ORIGINAL_MODEL" ]; then
          echo "Model tidak ditemukan di /tmp! Kita kalah."
          exit 1
        fi
        
        echo "BINGO! Model berhasil diculik dari: $ORIGINAL_MODEL"
        cp -r "$ORIGINAL_MODEL" ./deploy_model
        
        echo "=== ISI FOLDER SIAP DEPLOY ==="
        ls -la ./deploy_model

    - name: Build Docker Model
      run: |
        # Tag v6: Tanda berakhirnya drama
        mlflow models build-docker -m ./deploy_model -n "${{ secrets.DOCKER_USERNAME }}/churn-model:v6"

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/churn-model:v6